import { Link, useParams } from "react-router-dom";
import { Alert, Badge } from "../../../../design-system/aurora";
import { mapProductIntelligence } from "../../adapters/map-product-intelligence";
import { useProductDetail } from "../../queries/use-product-intelligence";
import { CanonicalPrice } from "./CanonicalPrice";
import { OfferingNavigation } from "./OfferingNavigation";
import { ProductSection } from "./ProductSection";
const lifecycle = { ACTIVE: "Active", DRAFT_INCOMPLETE: "Draft incomplete", PAUSED_INACTIVE: "Paused" } as const;
export function OfferingDetail() { const { offeringId = "" } = useParams(); const { state, refresh } = useProductDetail(offeringId); const view = state.data ? mapProductIntelligence(state.data) : undefined; return <div className="product-workspace"><OfferingNavigation/><main className="product-page"><Link className="back-link" to="/brand-centre/offerings">← All Offerings</Link>{state.status === "LOADING" ? <p role="status">Loading Product Intelligence…</p> : null}{state.status === "ERROR" && !view ? <Alert tone="error" title="Could not load this Offering">Product information is temporarily unavailable.</Alert> : null}{view ? <><header className="offering-identity"><div><p className="eyebrow">{view.offering.kind ?? "Offering"}{view.offering.subtype ? ` · ${view.offering.subtype}` : ""}</p><h1>{view.offering.name}</h1>{view.offering.description ? <p>{view.offering.description}</p> : null}<a href={view.offering.customerDestination} target="_blank" rel="noreferrer">View customer destination</a></div><Badge tone={view.offering.lifecycle.state === "RESOLVED" && view.offering.lifecycle.value === "ACTIVE" ? "success" : "neutral"}>{view.offering.lifecycle.state === "RESOLVED" ? lifecycle[view.offering.lifecycle.value] : "Historical status unresolved"}</Badge></header><CanonicalPrice offeringId={offeringId} price={view.offering.canonicalPrice} view={view} onSaved={refresh}/><div className="intelligence-heading"><p className="eyebrow">Product Intelligence</p><h2>Grounded Offering understanding</h2></div>{view.sections.map((section) => <ProductSection key={section.title} section={section}/>)}</> : null}</main></div>; }
