import type { CollaborationActor, CollaborationDetailResponse } from "../../contracts/collaboration.contracts";
import { collaborationStageLabel } from "../../utils/stage-labels";

const reasonCopy: Record<string, string> = {
  BRAND_EXIT_PRE_SECUREMENT: "The Brand ended the collaboration before funds were secured.", PRE_SECUREMENT_EXIT: "The collaboration ended before funds were secured.", CREATOR_EXIT_PRE_SECUREMENT: "The Creator cancelled the collaboration before funds were secured.",
  BRAND_EXIT_POST_SECUREMENT: "The Brand ended the collaboration after funds were secured.", BRAND_PROTECTED_POST_SECUREMENT_EXIT: "The Brand ended the collaboration after funds were secured.", CREATOR_CANCELLED_POST_SECUREMENT: "The Creator cancelled the collaboration.", CREATOR_CANCELLED: "The Creator cancelled the collaboration.",
  CREATOR_NON_PERFORMANCE: "The required Creator action was not completed.", CREATOR_PUBLISHING_NON_PERFORMANCE: "The required publishing action was not completed.", FULFILLMENT_HARD_STOP: "Fulfillment could not be completed after the permitted attempts.", PRODUCTION_HARD_STOP: "The final permitted revision was not approved.", BRAND_DECLINED_PUBLICATION: "The Brand declined publication for this deliverable.", ADMIN_RESOLUTION: "Creator Shop resolved this collaboration after review.", NEGOTIATION_DECLINED: "The proposed terms were declined.", BRAND_DECLINED: "The Brand declined the proposed terms.", CREATOR_DECLINED: "The Creator declined the proposed terms.",
};
const actorCopy: Record<CollaborationActor, string> = { BRAND: "Brand ended", CREATOR: "Creator cancelled", SYSTEM: "System ended", ADMIN: "Admin resolved", NONE: "No actor attribution" };
function money(currency: string | null, amount: number | null) { return `${currency ?? ""} ${amount ?? 0}`.trim(); }
const legCopy: Record<string, string> = { NOT_REQUIRED: "Not required", PENDING: "Pending", PROCESSING: "Processing", CONFIRMED: "Confirmed", BLOCKED: "Delayed" };
function TerminalSettlementSummary({ detail }: { detail: CollaborationDetailResponse }) { const settlement = detail.settlement; return <article className="collab-exec-card collab-settlement"><h5>Residual settlement execution</h5><p>{settlement.state === "SETTLED" ? "Settlement completed" : settlement.state === "PROCESSING" ? "Settlement processing" : settlement.state === "ELIGIBLE" ? "Settlement is ready for processing" : settlement.state === "BLOCKED" ? "Settlement execution is blocked" : "Settlement is not yet eligible"}</p>{settlement.blockedReason ? <p>{settlement.blockedReason}</p> : null}<dl className="collab-facts">{settlement.creatorPayoutState ? <div><dt>Creator payout</dt><dd>{legCopy[settlement.creatorPayoutState] ?? "Status available"}</dd></div> : null}{settlement.brandRefundState ? <div><dt>Brand refund execution</dt><dd>{legCopy[settlement.brandRefundState] ?? "Status available"}</dd></div> : null}{settlement.settledAt ? <div><dt>Settled</dt><dd>{new Date(settlement.settledAt).toLocaleString()}</dd></div> : null}{settlement.blockedAt ? <div><dt>Blocked</dt><dd>{new Date(settlement.blockedAt).toLocaleString()}</dd></div> : null}<div><dt>Residual settlement</dt><dd>{settlement.residualSettlementPending ? "Pending" : "None pending"}</dd></div></dl><p>Financial entitlement and money execution are separate.</p></article>; }

export function ResolutionCard({ detail }: { detail: CollaborationDetailResponse }) {
  const resolution = detail.resolution; const reason = detail.lifecycle.endedReason;
  return <section className="collab-resolution-stack" aria-labelledby="collab-resolution-title"><article className="collab-exec-card collab-resolution"><h4 id="collab-resolution-title">Collaboration {detail.lifecycle.state === "CANCELLED" ? "cancelled" : "ended"}</h4><p>{reason?.text ?? (reason?.code ? reasonCopy[reason.code] : null) ?? "This collaboration is no longer in active execution."}</p><dl className="collab-facts">{detail.lifecycle.endedFromStage ? <div><dt>Ended during</dt><dd>{collaborationStageLabel(detail.lifecycle.endedFromStage)}</dd></div> : null}{detail.lifecycle.endedAt ? <div><dt>Ended</dt><dd>{new Date(detail.lifecycle.endedAt).toLocaleString()}</dd></div> : null}{detail.lifecycle.endedByActorClass ? <div><dt>Outcome initiated by</dt><dd>{actorCopy[detail.lifecycle.endedByActorClass]}</dd></div> : null}</dl>{resolution ? <section className="collab-financial-resolution" aria-labelledby="terminal-financial-title"><h5 id="terminal-financial-title">Financial resolution</h5><dl className="collab-facts"><div><dt>Creator entitlement</dt><dd>{money(resolution.currency, resolution.creatorGrossEntitlementAmount ?? resolution.creatorEntitlementAmount)}</dd></div><div><dt>Brand refund entitlement</dt><dd>{money(resolution.currency, resolution.brandCommercialRefundEntitlementAmount ?? resolution.brandRefundEntitlementAmount)}</dd></div>{resolution.platformCommissionRetainedAmount != null ? <div><dt>Platform commission retained</dt><dd>{money(resolution.currency, resolution.platformCommissionRetainedAmount)}</dd></div> : null}{resolution.platformCommissionRefundAmount != null ? <div><dt>Platform commission refund</dt><dd>{money(resolution.currency, resolution.platformCommissionRefundAmount)}</dd></div> : null}{resolution.platformCommissionGstRetainedAmount != null ? <div><dt>GST retained</dt><dd>{money(resolution.currency, resolution.platformCommissionGstRetainedAmount)}</dd></div> : null}{resolution.platformCommissionGstRefundAmount != null ? <div><dt>GST refund</dt><dd>{money(resolution.currency, resolution.platformCommissionGstRefundAmount)}</dd></div> : null}<div><dt>Resolution status</dt><dd>{resolution.resolvedAt ? "Resolved" : "Pending resolution"}</dd></div></dl></section> : <p>No financial resolution is projected for this outcome.</p>}</article><TerminalSettlementSummary detail={detail} /></section>;
}
