import type { ProductConsumer } from "../schemas/product-intelligence-schema";
type Item = { id: string; text: string };
export type ProductSectionView = { title: string; readiness: "READY" | "PARTIAL" | "NOT_READY"; freshness: "CURRENT" | "STALE" | "UNKNOWN"; activity: string; hasCurrent: boolean; summary?: string; groups: { label: string; items: Item[] }[]; candidate: "NONE" | "AVAILABLE" | "CONFLICT"; failedWithCurrent: boolean };
export type ProductView = { offering: ProductConsumer["offering"]; priceLabel: string; manuallyManaged: boolean; sections: ProductSectionView[] };
const record = (value: unknown): Record<string, unknown> => value && typeof value === "object" && !Array.isArray(value) ? value as Record<string, unknown> : {};
const items = (value: unknown): Item[] => Array.isArray(value) ? value.flatMap((item, index) => { if (typeof item === "string") return [{ id: String(index), text: item }]; const row = record(item); const text = [row.text, row.fact, row.benefit, row.proof, row.context, row.action].find((v) => typeof v === "string"); return typeof text === "string" ? [{ id: typeof row.semantic_id === "string" ? row.semantic_id : String(index), text }] : []; }) : typeof value === "string" ? [{ id: "value", text: value }] : [];
function section(title: string, object: ProductConsumer["intelligence"][keyof ProductConsumer["intelligence"]], runtime: ProductConsumer["processorRuntime"][keyof ProductConsumer["processorRuntime"]], fields: [string, string][]): ProductSectionView { const value = object.current.kind === "VALUE" ? record(object.current.value) : {}; return { title, readiness: object.readiness, freshness: object.freshness, activity: runtime.activity, hasCurrent: object.current.kind === "VALUE", summary: typeof value.factual_summary === "string" ? value.factual_summary : undefined, groups: fields.map(([key, label]) => ({ label, items: items(value[key]) })).filter((group) => group.items.length), candidate: object.candidate.status, failedWithCurrent: runtime.activity === "TEMPORARILY_UNAVAILABLE" && runtime.hasCurrent }; }
function priceLabel(price: ProductConsumer["offering"]["canonicalPrice"]) { if (price.state === "UNAVAILABLE") return "Price not established"; if (price.mode === "NOT_PUBLICLY_LISTED") return "Not publicly listed"; const format = (amount: string | null) => amount == null ? "—" : new Intl.NumberFormat(undefined, { style: "currency", currency: price.currency }).format(Number(amount)); if (price.mode === "STARTING_AT") return `Starting at ${format(price.currentMinAmount)}`; if (price.mode === "RANGE") return `${format(price.currentMinAmount)}–${format(price.currentMaxAmount)}`; return format(price.currentMinAmount); }
export function mapProductIntelligence(data: ProductConsumer): ProductView { return { offering: data.offering, priceLabel: priceLabel(data.offering.canonicalPrice), manuallyManaged: data.offering.canonicalPrice.state === "CURRENT" && data.offering.canonicalPrice.authority === "BRAND_CONFIRMED", sections: [section("Factual understanding", data.intelligence.factualProfile, data.processorRuntime.offering_factual_synthesis, [["key_facts", "Key facts"], ["key_benefits", "Key benefits"], ["proof_points", "Proof points"], ["usage_context", "Usage context"], ["customer_context", "Customer context"]]), section("Creator communication", data.intelligence.creatorCommunicationProfile, data.processorRuntime.offering_creator_communication, [["creator_talking_points", "Creator talking points"], ["communication_constraints", "Communication constraints"]]), section("Actionability", data.intelligence.actionabilityProfile, data.processorRuntime.offering_actionability_synthesis, [["customer_action", "Customer action"], ["commercial_context", "Commercial context"]])] }; }
