/** Product Amendment 1. Creator positioning, not Brand industry/preferences. */
export const CREATOR_BRAND_NICHE_IDS = [
  "BEAUTY",
  "FASHION",
  "LIFESTYLE",
  "HEALTH_WELLNESS",
  "FITNESS",
  "FOOD_COOKING",
  "TRAVEL",
  "PARENTING_FAMILY",
  "HOME_INTERIORS",
  "TECHNOLOGY",
  "GAMING",
  "EDUCATION",
  "CAREER_PRODUCTIVITY",
  "BUSINESS_ENTREPRENEURSHIP",
  "PERSONAL_FINANCE",
  "ARTS_CULTURE",
  "ENTERTAINMENT_COMEDY",
  "MUSIC",
  "PHOTOGRAPHY_FILM",
  "BOOKS_WRITING",
  "SPORTS",
  "AUTOMOTIVE",
  "PETS_ANIMALS",
  "SUSTAINABILITY",
  "DIY_CRAFTS",
  "RELATIONSHIPS",
  "SPIRITUALITY_MINDFULNESS",
] as const;
export const CREATOR_BRAND_VOICE_IDS = [
  "EDUCATIONAL",
  "WARM",
  "DIRECT",
  "PLAYFUL",
  "ASPIRATIONAL",
  "PRACTICAL",
  "ANALYTICAL",
  "CONVERSATIONAL",
  "BOLD",
  "HUMOROUS",
  "CALM",
  "ENERGETIC",
] as const;
export const CREATOR_BRAND_BOUNDS = Object.freeze({
  primaryNiches: 3,
  configuredArchetypes: 3,
  voiceDescriptors: 3,
  voiceDescriptionCharacters: 300,
  visualDescriptors: 5,
  paletteColors: 5,
  languages: 10,
  // Technical text limits; not additional categories or completion requirements.
  headlineCharacters: 160,
  commercialBioCharacters: 1000,
  visualDescriptorCharacters: 100,
});
