import { describe, expect, it } from "vitest";
import { canonicalOfferingIndexSchema, manualPriceInputSchema, productConsumerSchema } from "./product-intelligence-schema";
import { productFixture } from "../testing/product-intelligence-fixtures";
const ids = ["11111111-1111-4111-8111-111111111111", "22222222-2222-4222-8222-222222222222", "33333333-3333-4333-8333-333333333333", "44444444-4444-4444-8444-444444444444"];
describe("canonical Offering discovery contract", () => {
  it("parses an empty truthful index", () => expect(canonicalOfferingIndexSchema.parse({ offerings: [] }).offerings).toEqual([]));
  it("retains backend order and exact IDs", () => { const input = { offerings: ids.slice(0,2).map((offeringId, i) => ({ offeringId, name: `Offering ${i}`, kind: "PRODUCT", subtype: null, lifecycle: "ACTIVE" })) }; expect(canonicalOfferingIndexSchema.parse(input).offerings.map((x) => x.offeringId)).toEqual(ids.slice(0,2)); });
  it.each(["PRODUCT", "SERVICE", "EXPERIENCE", "BUNDLE"] as const)("parses kind %s", (kind) => expect(canonicalOfferingIndexSchema.safeParse({ offerings: [{ offeringId: ids[0], name: "A", kind, subtype: null, lifecycle: "ACTIVE" }] }).success).toBe(true));
  it.each(["ACTIVE", "DRAFT_INCOMPLETE", "PAUSED_INACTIVE"] as const)("parses lifecycle %s", (lifecycle) => expect(canonicalOfferingIndexSchema.safeParse({ offerings: [{ offeringId: ids[0], name: "A", kind: "PRODUCT", subtype: null, lifecycle }] }).success).toBe(true));
  it("rejects unknown kind and lifecycle", () => { expect(canonicalOfferingIndexSchema.safeParse({ offerings: [{ offeringId: ids[0], name: "A", kind: "OTHER", subtype: null, lifecycle: "ACTIVE" }] }).success).toBe(false); expect(canonicalOfferingIndexSchema.safeParse({ offerings: [{ offeringId: ids[0], name: "A", kind: "PRODUCT", subtype: null, lifecycle: "UNRESOLVED" }] }).success).toBe(false); });
  it("rejects legacy enrichment and needs no price/intelligence/runtime", () => { expect(canonicalOfferingIndexSchema.safeParse({ offerings: [{ offeringId: ids[0], name: "A", kind: "PRODUCT", subtype: null, lifecycle: "ACTIVE", isDeepScanned: true }] }).success).toBe(false); expect(canonicalOfferingIndexSchema.safeParse({ offerings: [{ offeringId: ids[0], name: "A", kind: "PRODUCT", subtype: null, lifecycle: "ACTIVE" }] }).success).toBe(true); });
});
describe("exact Product contract", () => {
  it("parses a strict valid response", () => expect(productConsumerSchema.parse(productFixture).offering.id).toBe(ids[0]));
  it("fails safely on malformed and unknown top-level fields", () => { expect(productConsumerSchema.safeParse({ ...productFixture, ready: true }).success).toBe(false); expect(productConsumerSchema.safeParse({ ...productFixture, offering: { ...productFixture.offering, id: "bad" } }).success).toBe(false); });
  it("keeps all three Object identities independent", () => { const bad = structuredClone(productFixture); bad.intelligence.creatorCommunicationProfile.semanticId = "offering_factual_profile" as never; expect(productConsumerSchema.safeParse(bad).success).toBe(false); });
  it("keeps all three runtime identities independent", () => { const bad = structuredClone(productFixture); bad.processorRuntime.offering_creator_communication.processorId = "offering_factual_synthesis" as never; expect(productConsumerSchema.safeParse(bad).success).toBe(false); });
  it("contains no Product-wide readiness", () => expect("readiness" in productConsumerSchema.parse(productFixture)).toBe(false));
  it("preserves stale current, failed refresh and candidate metadata", () => { const value = structuredClone(productFixture); value.intelligence.factualProfile.freshness = "STALE"; value.processorRuntime.offering_factual_synthesis.activity = "TEMPORARILY_UNAVAILABLE"; value.processorRuntime.offering_factual_synthesis.failure = { category: null, code: "RETRY", currentPreserved: true, retryEligible: true }; value.intelligence.factualProfile.candidate = { ...value.intelligence.factualProfile.candidate, status: "CONFLICT", count: 1, currentPreserved: true, summaryAvailable: true }; const parsed = productConsumerSchema.parse(value); expect(parsed.intelligence.factualProfile.current.kind).toBe("VALUE"); expect(parsed.processorRuntime.offering_factual_synthesis.failure?.currentPreserved).toBe(true); expect(parsed.intelligence.factualProfile.candidate.status).toBe("CONFLICT"); });
  it.each(["EXACT", "STARTING_AT", "RANGE", "NOT_PUBLICLY_LISTED"] as const)("parses price mode %s", (mode) => expect(productConsumerSchema.safeParse({ ...productFixture, offering: { ...productFixture.offering, canonicalPrice: { ...productFixture.offering.canonicalPrice, mode } } }).success).toBe(true));
  it("parses unavailable, stale, unknown and protected price", () => { expect(productConsumerSchema.safeParse({ ...productFixture, offering: { ...productFixture.offering, canonicalPrice: { state: "UNAVAILABLE" } } }).success).toBe(true); for (const freshness of ["STALE", "UNKNOWN"] as const) expect(productConsumerSchema.safeParse({ ...productFixture, offering: { ...productFixture.offering, canonicalPrice: { ...productFixture.offering.canonicalPrice, freshness } } }).success).toBe(true); expect(productConsumerSchema.parse(productFixture).offering.canonicalPrice.state).toBe("CURRENT"); });
});
describe("manual price DTO", () => {
  it.each([{ mode: "EXACT", currentMinAmount: "25", currentMaxAmount: "25", currency: "USD" }, { mode: "STARTING_AT", currentMinAmount: "10", currency: "USD" }, { mode: "RANGE", currentMinAmount: "10", currentMaxAmount: "20", currency: "USD" }, { mode: "NOT_PUBLICLY_LISTED", currency: "USD" }] as const)("accepts $mode", (input) => expect(manualPriceInputSchema.safeParse(input).success).toBe(true));
  it("rejects invalid tuples", () => expect(manualPriceInputSchema.safeParse({ mode: "RANGE", currentMinAmount: "20", currentMaxAmount: "10", currency: "USD" }).success).toBe(false));
});
