import type { ReactNode } from "react";
import type { CanonicalReadinessCurrency } from "../../api/canonical-campaign-draft-client";
import type { WizardData, WizardFieldErrors, WizardFieldKey } from "../../types/campaign-wizard";
import { getFieldError } from "../../utils/validate-campaign-wizard";
import { CurrencyAmountField } from "./CurrencyAmountField";
import { ADVANCE_OPTIONS, COMPENSATION_OPTIONS, PAYOUT_OPTIONS, SUPPORT_OPTIONS, compensationPresentation, payoutTermsHelper, supportDisabledPatch } from "./commercial-strategy-model";
import "./commercial-strategy.css";

type Props = { data: WizardData; currency: CanonicalReadinessCurrency; patchData: (patch: Partial<WizardData>, touched?: WizardFieldKey) => void; errors: WizardFieldErrors; validateOnExit: (field: WizardFieldKey) => Promise<void> };
function Section({ id, title, description, children }: { id: string; title: string; description: string; children: ReactNode }) { return <section className="commercial-section" aria-labelledby={id}><div className="commercial-section__head"><h2 id={id}>{title}</h2><p>{description}</p></div>{children}</section>; }
function Field({ id, label, optional, error, helper, children }: { id: string; label: string; optional?: boolean; error?: string; helper?: string; children: ReactNode }) { return <div className={`cw-field ${error ? "cw-field--error" : ""}`}><label className="cw-label" htmlFor={id}>{label}{optional ? <span className="commercial-optional">Optional</span> : <span className="cw-required">Required</span>}</label>{children}{helper ? <p className="cw-hint" id={`${id}-helper`}>{helper}</p> : null}{error ? <p className="cw-field-error" id={`${id}-error`} role="alert">{error}</p> : null}</div>; }
function ChoiceCards<T extends string | number>({ name, value, options, onChange, onBlur, compact = false }: { name: string; value: T; options: ReadonlyArray<{ value: T; label: string }>; onChange: (value: T) => void; onBlur: () => void; compact?: boolean }) { return <div className={`commercial-choice-grid ${compact ? "commercial-choice-grid--advance" : ""}`}>{options.map((option) => <label key={option.value} className={`commercial-choice ${value === option.value ? "is-selected" : ""}`}><input type="radio" name={name} checked={value === option.value} onChange={() => onChange(option.value)} onBlur={onBlur} /><span>{option.label}</span></label>)}</div>; }

export function CommercialStrategyStep({ data, currency, patchData, errors, validateOnExit }: Props) {
  const compensation = compensationPresentation(data.compensationModel);
  return <div className="create-wizard-step commercial-strategy-step"><header className="create-wizard-step-head"><h1>Commercial Strategy</h1><p>Set Brand support, creator compensation, Campaign budget and payment timing.</p></header>
    <Section id="creator-provisioning-heading" title="Creator Provisioning" description="Define any non-cash support supplied to each creator."><div className="commercial-grid"><fieldset className="cw-field commercial-fieldset"><legend className="cw-label">Will creators receive support from your Brand?</legend><ChoiceCards name="brand-support" value={data.receivesBrandSupport ? "YES" : "NO"} options={[{ value: "YES", label: "Yes" }, { value: "NO", label: "No" }]} onChange={(value) => patchData(value === "YES" ? { receivesBrandSupport: true } : supportDisabledPatch(), "receivesBrandSupport")} onBlur={() => void validateOnExit("receivesBrandSupport")} /></fieldset>{data.receivesBrandSupport ? <><Field id="brand-support-type" label="Brand Support Type" error={getFieldError(errors, "brandSupportType")}><select id="brand-support-type" className="cw-input cw-select" value={data.brandSupportType ?? ""} aria-describedby="brand-support-type-error" onChange={(event) => patchData({ brandSupportType: (event.target.value || null) as WizardData["brandSupportType"] }, "brandSupportType")} onBlur={() => void validateOnExit("brandSupportType")}><option value="">Select support type</option>{SUPPORT_OPTIONS.map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</select></Field><Field id="estimated-value" label="Estimated Value" optional error={getFieldError(errors, "brandSupportEstimatedValue")} helper="Estimated value of the support provided to each creator."><CurrencyAmountField id="estimated-value" value={data.brandSupportEstimatedValue} optional currency={currency} describedBy="estimated-value-helper estimated-value-error" onChange={(brandSupportEstimatedValue) => patchData({ brandSupportEstimatedValue }, "brandSupportEstimatedValue")} onBlur={() => void validateOnExit("brandSupportEstimatedValue")} /></Field></> : null}</div></Section>
    <Section id="creator-compensation-heading" title="Creator Compensation" description="Choose how the offer is presented to each creator."><div className="commercial-grid"><fieldset className="cw-field commercial-fieldset"><legend className="cw-label">Compensation Structure</legend><ChoiceCards name="compensation-model" value={data.compensationModel} options={COMPENSATION_OPTIONS} onChange={(compensationModel) => patchData({ compensationModel }, "compensationModel")} onBlur={() => void validateOnExit("compensationModel")} /></fieldset><Field id="commercial-offer" label={compensation.label} error={getFieldError(errors, "commercialOffer")} helper={compensation.helper}><CurrencyAmountField id="commercial-offer" value={data.commercialOffer} currency={currency} describedBy="commercial-offer-helper commercial-offer-error" onChange={(commercialOffer) => patchData({ commercialOffer: commercialOffer ?? 0 }, "commercialOffer")} onBlur={() => void validateOnExit("commercialOffer")} /></Field></div></Section>
    <Section id="campaign-budget-heading" title="Campaign Budget" description="Set the Campaign-wide budget reserved for creator payouts."><Field id="campaign-budget" label="Total Campaign Budget" error={getFieldError(errors, "totalCampaignBudget")} helper="Used across creator payouts for this Campaign. Brand support value is tracked separately."><CurrencyAmountField id="campaign-budget" value={data.totalCampaignBudget} currency={currency} describedBy="campaign-budget-helper campaign-budget-error" onChange={(totalCampaignBudget) => patchData({ totalCampaignBudget: totalCampaignBudget ?? 0 }, "totalCampaignBudget")} onBlur={() => void validateOnExit("totalCampaignBudget")} /></Field></Section>
    <Section id="payment-terms-heading" title="Payment Terms" description="Set the advance and remaining payout timing."><div className="commercial-grid"><fieldset className={`cw-field commercial-fieldset ${getFieldError(errors, "advancePaymentPercentage") ? "cw-field--error" : ""}`}><legend className="cw-label">Advance</legend><ChoiceCards compact name="advance" value={data.advancePaymentPercentage} options={ADVANCE_OPTIONS.map((value) => ({ value, label: `${value}%` }))} onChange={(advancePaymentPercentage) => patchData({ advancePaymentPercentage }, "advancePaymentPercentage")} onBlur={() => void validateOnExit("advancePaymentPercentage")} />{getFieldError(errors, "advancePaymentPercentage") ? <p className="cw-field-error" role="alert">{getFieldError(errors, "advancePaymentPercentage")}</p> : null}</fieldset><Field id="payout-terms" label="Payout Terms" error={getFieldError(errors, "payoutTerms")} helper={payoutTermsHelper(data.payoutTerms)}><select id="payout-terms" className="cw-input cw-select" value={data.payoutTerms} aria-describedby="payout-terms-helper payout-terms-error" onChange={(event) => patchData({ payoutTerms: event.target.value as WizardData["payoutTerms"] }, "payoutTerms")} onBlur={() => void validateOnExit("payoutTerms")}>{PAYOUT_OPTIONS.map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</select></Field></div></Section>
  </div>;
}
