import { useEffect, useState, type FormEvent } from "react";
import { Alert, Button, TextField } from "../../../../design-system/aurora";
import type { UserRole } from "../../../../shared/auth/user-role";
import type { CollaborationDeliverable, CollaborationDetailResponse } from "../../contracts/collaboration.contracts";
import { deliverableHasCapability } from "../../utils/collaboration-capabilities";
import { BlockingCard } from "../execution/BlockingCard";
import { PublishingEvidenceHistory } from "./PublishingEvidenceHistory";

type Props = { detail: CollaborationDetailResponse; deliverable: CollaborationDeliverable; role: UserRole; busyAction: string | null; onAuthorize: (id: string) => void; onDecline: (id: string) => void; onSubmitEvidence: (id: string, evidenceRef: string, platform?: string, note?: string) => void; onSubmitCorrection: (id: string, evidenceRef: string, platform?: string, note?: string) => void; onVerify: (id: string, evidenceId: string, complianceRef?: string) => void; onRequestCorrection: (id: string, evidenceId: string, reason: string) => void };
const stateCopy = { AWAITING_PUBLISHING: "Publishing approved", EVIDENCE_SUBMITTED: "Submitted for verification", CORRECTION_REQUIRED: "Correction requested", COMPLIANCE_VERIFIED: "Publishing verified", BLOCKED: "Publishing under review", PUBLISHING_NOT_REQUIRED: "Publishing not required" } as const;

export function PublishingDeliverableCard({ detail, deliverable, role, busyAction, onAuthorize, onDecline, onSubmitEvidence, onSubmitCorrection, onVerify, onRequestCorrection }: Props) {
  const publishing = deliverable.publishing;
  const definition = deliverable.definitionSnapshot;
  const title = typeof definition.title === "string" ? definition.title : `Deliverable ${deliverable.displayOrder}`;
  const active = publishing?.activeEvidence;
  const [evidenceRef, setEvidenceRef] = useState(""); const [platform, setPlatform] = useState(""); const [note, setNote] = useState(""); const [evidenceError, setEvidenceError] = useState<string>();
  const [complianceRef, setComplianceRef] = useState(""); const [correctionReason, setCorrectionReason] = useState(""); const [correctionError, setCorrectionError] = useState<string>();
  useEffect(() => { setEvidenceRef(""); setPlatform(""); setNote(""); setEvidenceError(undefined); setComplianceRef(""); setCorrectionReason(""); setCorrectionError(undefined); }, [active?.publishingEvidenceId, publishing?.state]);
  const key = (action: string, evidenceId?: string) => `${action}:${deliverable.deliverableExecutionId}${evidenceId ? `:${evidenceId}` : ""}`;
  const cardBusy = busyAction?.includes(`:${deliverable.deliverableExecutionId}`) ?? false;
  if (!deliverable.publishingRequired || !publishing || publishing.state === "PUBLISHING_NOT_REQUIRED") return <article className="collab-exec-card collab-publishing-card"><h5>{title}</h5><Alert tone="success" title="Publishing not required">No publishing evidence or action is required for this deliverable.</Alert></article>;
  const submitEvidence = (event: FormEvent) => { event.preventDefault(); if (!evidenceRef.trim()) { setEvidenceError("Add a published content link or reference."); return; } setEvidenceError(undefined); const action = deliverableHasCapability(deliverable, "submit-corrected-evidence") ? onSubmitCorrection : onSubmitEvidence; action(deliverable.deliverableExecutionId, evidenceRef.trim(), platform.trim() || undefined, note.trim() || undefined); };
  const requestCorrection = (event: FormEvent) => { event.preventDefault(); if (correctionReason.trim().length < 3) { setCorrectionError("Describe what needs to be corrected."); return; } setCorrectionError(undefined); onRequestCorrection(deliverable.deliverableExecutionId, active!.publishingEvidenceId, correctionReason.trim()); };
  const decline = () => { if (window.confirm("Decline publishing for this deliverable? The collaboration outcome will be determined by the agreed terms.")) onDecline(deliverable.deliverableExecutionId); };
  return <article className="collab-exec-card collab-publishing-card" aria-labelledby={`publishing-${deliverable.deliverableExecutionId}`}><header><h5 id={`publishing-${deliverable.deliverableExecutionId}`}>{title}</h5><strong role="status">{stateCopy[publishing.state]}</strong></header>
    {deliverable.state === "APPROVED" && publishing.authorizationState === "AUTHORIZED" ? <Alert tone="success" title="Approved by Brand">Publishing is authorized for this deliverable.</Alert> : null}
    {deliverable.state === "AUTO_APPROVED" && publishing.authorizationState === "NOT_AUTHORIZED" ? <Alert tone="warning" title="Waiting for Brand publishing approval">Content was auto-approved because the review window expired. Brand publishing approval is still required.</Alert> : null}
    {deliverableHasCapability(deliverable, "authorize-publishing") || deliverableHasCapability(deliverable, "decline-publishing") ? <div className="collab-exec-actions" aria-busy={cardBusy}>{deliverableHasCapability(deliverable, "authorize-publishing") ? <Button disabled={cardBusy} onClick={() => onAuthorize(deliverable.deliverableExecutionId)} fullWidthOnMobile>{busyAction === key("authorize") ? "Authorizing…" : "Authorize publishing"}</Button> : null}{deliverableHasCapability(deliverable, "decline-publishing") ? <Button variant="secondary" disabled={cardBusy} onClick={decline} fullWidthOnMobile>{busyAction === key("decline") ? "Declining…" : "Decline publishing"}</Button> : null}</div> : null}
    {(deliverableHasCapability(deliverable, "submit-publishing-evidence") || deliverableHasCapability(deliverable, "submit-corrected-evidence")) ? <form className="collab-command-form" onSubmit={submitEvidence} aria-busy={busyAction === key(deliverableHasCapability(deliverable, "submit-corrected-evidence") ? "submit-correction" : "submit-evidence")}><h6>{deliverableHasCapability(deliverable, "submit-corrected-evidence") ? "Submit corrected publishing evidence" : "Submit publishing evidence"}</h6>{publishing.correctionReason ? <p><strong>Brand correction feedback:</strong> {publishing.correctionReason}</p> : null}<TextField label="Published content link or reference" value={evidenceRef} onChange={(event) => { setEvidenceRef(event.target.value); setEvidenceError(undefined); }} error={evidenceError} disabled={cardBusy} /><TextField label="Platform (optional)" value={platform} onChange={(event) => setPlatform(event.target.value)} disabled={cardBusy} /><TextField label="Creator note (optional)" multiline value={note} onChange={(event) => setNote(event.target.value)} disabled={cardBusy} /><Button type="submit" disabled={cardBusy} fullWidthOnMobile>{cardBusy ? "Submitting…" : "Submit for verification"}</Button></form> : null}
    {publishing.state === "EVIDENCE_SUBMITTED" && role === "CREATOR" ? <Alert tone="warning" title="Submitted for verification">Waiting for the Brand to verify publishing.</Alert> : null}
    {deliverableHasCapability(deliverable, "verify-publishing") && active ? <form className="collab-command-form" onSubmit={(event) => { event.preventDefault(); onVerify(deliverable.deliverableExecutionId, active.publishingEvidenceId, complianceRef.trim() || undefined); }} aria-busy={busyAction === key("verify", active.publishingEvidenceId)}><h6>Verify publishing</h6><p>Confirm only the publishing requirement. Settlement is processed separately.</p><TextField label="Compliance reference (optional)" value={complianceRef} onChange={(event) => setComplianceRef(event.target.value)} disabled={cardBusy} /><Button type="submit" disabled={cardBusy} fullWidthOnMobile>{busyAction === key("verify", active.publishingEvidenceId) ? "Verifying…" : "Verify publishing"}</Button></form> : null}
    {deliverableHasCapability(deliverable, "request-publishing-correction") && active ? <form className="collab-command-form" onSubmit={requestCorrection} aria-busy={busyAction === key("correct", active.publishingEvidenceId)}><h6>Request correction</h6><TextField label="Describe what needs to be corrected" multiline value={correctionReason} onChange={(event) => { setCorrectionReason(event.target.value); setCorrectionError(undefined); }} error={correctionError} disabled={cardBusy} /><Button type="submit" variant="secondary" disabled={cardBusy} fullWidthOnMobile>{busyAction === key("correct", active.publishingEvidenceId) ? "Requesting…" : "Request correction"}</Button></form> : null}
    {publishing.state === "COMPLIANCE_VERIFIED" ? <Alert tone="success" title="Publishing verified">The publishing requirement is complete. Settlement status is shown separately.</Alert> : null}
    {publishing.state === "BLOCKED" ? <BlockingCard detail={detail} reason={publishing.blockedReason} actionRequiredBy={deliverable.actionRequiredBy} /> : null}
    <PublishingEvidenceHistory evidence={publishing.evidenceHistory} />
  </article>;
}
