import { useEffect, useState, type FormEvent } from "react";
import { Send } from "lucide-react";
import { Alert, Button, TextField } from "../../../../design-system/aurora";
import type { UserRole } from "../../../../shared/auth/user-role";
import type { CollaborationDeliverable, CollaborationDetailResponse } from "../../contracts/collaboration.contracts";
import { deliverableHasCapability } from "../../utils/collaboration-capabilities";
import { BlockingCard } from "../execution/BlockingCard";
import { PublishingEvidenceHistory } from "./PublishingEvidenceHistory";

type Props = { detail: CollaborationDetailResponse; deliverable: CollaborationDeliverable; role: UserRole; busyAction: string | null; onAuthorize: (id: string) => void; onDecline: (id: string) => void; onSubmitEvidence: (id: string, evidenceRef: string, platform?: string, note?: string) => void; onSubmitCorrection: (id: string, evidenceRef: string, platform?: string, note?: string) => void; onVerify: (id: string, evidenceId: string, complianceRef?: string) => void; onRequestCorrection: (id: string, evidenceId: string, reason: string) => void };

function publishingStateLabel(deliverable: CollaborationDeliverable): string {
  const publishing = deliverable.publishing;
  if (!deliverable.publishingRequired || !publishing || publishing.state === "PUBLISHING_NOT_REQUIRED") return "Publishing not required";
  if (publishing.state === "AWAITING_PUBLISHING") return publishing.authorizationState === "AUTHORIZED" ? "Awaiting evidence" : "Awaiting authorization";
  if (publishing.state === "EVIDENCE_SUBMITTED") return "Awaiting verification";
  if (publishing.state === "CORRECTION_REQUIRED") return "Correction required";
  if (publishing.state === "COMPLIANCE_VERIFIED") return "Publishing verified";
  return "Publishing under review";
}

export function PublishingDeliverableCard({ detail, deliverable, role, busyAction, onAuthorize, onDecline, onSubmitEvidence, onSubmitCorrection, onVerify, onRequestCorrection }: Props) {
  const publishing = deliverable.publishing;
  const definition = deliverable.definitionSnapshot;
  const title = typeof definition.title === "string" ? definition.title : `Deliverable ${deliverable.displayOrder}`;
  const active = publishing?.activeEvidence;
  const [evidenceRef, setEvidenceRef] = useState(""); const [platform, setPlatform] = useState(""); const [note, setNote] = useState(""); const [evidenceError, setEvidenceError] = useState<string>();
  const [complianceRef, setComplianceRef] = useState(""); const [correctionReason, setCorrectionReason] = useState(""); const [correctionError, setCorrectionError] = useState<string>();
  useEffect(() => { setEvidenceRef(""); setPlatform(""); setNote(""); setEvidenceError(undefined); setComplianceRef(""); setCorrectionReason(""); setCorrectionError(undefined); }, [active?.publishingEvidenceId, publishing?.state]);
  const key = (action: string, evidenceId?: string) => `${action}:${deliverable.deliverableExecutionId}${evidenceId ? `:${evidenceId}` : ""}`;
  const cardBusy = busyAction?.includes(`:${deliverable.deliverableExecutionId}`) ?? false;
  const canAuthorize = deliverableHasCapability(deliverable, "authorize-publishing");
  const canDecline = deliverableHasCapability(deliverable, "decline-publishing");
  const canSubmitEvidence = deliverableHasCapability(deliverable, "submit-publishing-evidence");
  const canSubmitCorrection = deliverableHasCapability(deliverable, "submit-corrected-evidence");
  const canVerify = deliverableHasCapability(deliverable, "verify-publishing");
  const canRequestCorrection = deliverableHasCapability(deliverable, "request-publishing-correction");
  const isActionable = canAuthorize || canDecline || canSubmitEvidence || canSubmitCorrection || canVerify || canRequestCorrection;
  if (!deliverable.publishingRequired || !publishing || publishing.state === "PUBLISHING_NOT_REQUIRED") return <article className="collab-exec-card collab-publishing-card collab-publishing-card--not-required"><header className="collab-publishing-card__header"><span className="collab-deliverable__icon" aria-hidden="true"><Send size={18} /></span><div className="collab-deliverable__identity"><p className="collab-deliverable__eyebrow">Deliverable {deliverable.displayOrder}</p><h5>{title}</h5></div><strong className="collab-status-pill" role="status">Publishing not required</strong></header><div className="collab-publishing-card__intent"><strong>No publishing requirement</strong><span>This deliverable is intentionally complete without publishing authorization or evidence.</span></div></article>;
  const submitEvidence = (event: FormEvent) => { event.preventDefault(); if (!evidenceRef.trim()) { setEvidenceError("Add a published content link or reference."); return; } setEvidenceError(undefined); const action = deliverableHasCapability(deliverable, "submit-corrected-evidence") ? onSubmitCorrection : onSubmitEvidence; action(deliverable.deliverableExecutionId, evidenceRef.trim(), platform.trim() || undefined, note.trim() || undefined); };
  const requestCorrection = (event: FormEvent) => { event.preventDefault(); if (correctionReason.trim().length < 3) { setCorrectionError("Describe what needs to be corrected."); return; } setCorrectionError(undefined); onRequestCorrection(deliverable.deliverableExecutionId, active!.publishingEvidenceId, correctionReason.trim()); };
  const decline = () => { if (window.confirm("Decline publishing for this deliverable? The collaboration outcome will be determined by the agreed terms.")) onDecline(deliverable.deliverableExecutionId); };
  return <article className={`collab-exec-card collab-publishing-card${isActionable ? " collab-publishing-card--actionable" : ""}`} aria-labelledby={`publishing-${deliverable.deliverableExecutionId}`}><header className="collab-publishing-card__header"><span className="collab-deliverable__icon" aria-hidden="true"><Send size={18} /></span><div className="collab-deliverable__identity"><p className="collab-deliverable__eyebrow">Deliverable {deliverable.displayOrder}</p><h5 id={`publishing-${deliverable.deliverableExecutionId}`}>{title}</h5></div><div className="collab-deliverable__statuses">{isActionable ? <span className="collab-action-needed">Action needed</span> : null}<strong className={`collab-status-pill collab-status-pill--${publishing.state.toLowerCase().replace(/_/g, "-")}`} role="status">{publishingStateLabel(deliverable)}</strong></div></header>
    <div className={`collab-publishing-card__authorization collab-publishing-card__authorization--${publishing.authorizationState.toLowerCase().replace(/_/g, "-")}`}><strong>{publishing.authorizationState === "AUTHORIZED" ? "Publishing authorized" : "Publishing not authorized"}</strong><span>{publishing.authorizationState === "AUTHORIZED" ? publishing.authorizedAt ? `Authorized ${new Date(publishing.authorizedAt).toLocaleString()}` : "The Brand has authorized publication for this deliverable." : "Brand authorization is required before the Creator publishes."}</span></div>
    {deliverable.state === "AUTO_APPROVED" && publishing.authorizationState === "NOT_AUTHORIZED" ? <Alert tone="warning" title="Waiting for Brand publishing approval">Content was auto-approved because the review window expired. Brand publishing approval is still required.</Alert> : null}
    {canAuthorize || canDecline ? <section className="collab-publishing-card__command"><div><h6>Publishing decision</h6><p>Authorization applies only to this deliverable.</p></div><div className="collab-exec-actions" aria-busy={cardBusy}>{canAuthorize ? <Button disabled={cardBusy} onClick={() => onAuthorize(deliverable.deliverableExecutionId)} fullWidthOnMobile>{busyAction === key("authorize") ? "Authorizing…" : "Authorize publishing"}</Button> : null}{canDecline ? <Button variant="secondary" disabled={cardBusy} onClick={decline} fullWidthOnMobile>{busyAction === key("decline") ? "Declining…" : "Decline publishing"}</Button> : null}</div></section> : null}
    {active ? <dl className="collab-publishing-card__evidence"><div><dt>Published content</dt><dd className="collab-evidence-ref">{active.evidenceRef}</dd></div>{active.platform ? <div><dt>Platform</dt><dd>{active.platform}</dd></div> : null}<div><dt>Evidence version</dt><dd>Evidence {active.sequence}</dd></div><div><dt>Submitted</dt><dd>{new Date(active.submittedAt).toLocaleString()}</dd></div></dl> : publishing.authorizationState === "AUTHORIZED" ? <div className="collab-publishing-card__intent"><strong>Awaiting Creator publishing evidence</strong><span>No publishing evidence has been submitted yet.</span></div> : null}
    {(canSubmitEvidence || canSubmitCorrection) ? <form className="collab-command-form collab-publishing-card__command" onSubmit={submitEvidence} aria-busy={busyAction === key(canSubmitCorrection ? "submit-correction" : "submit-evidence")}><h6>{canSubmitCorrection ? "Submit corrected publishing evidence" : "Submit publishing evidence"}</h6>{publishing.correctionReason ? <p><strong>Brand correction feedback:</strong> {publishing.correctionReason}</p> : null}<TextField label="Published content link or reference" value={evidenceRef} onChange={(event) => { setEvidenceRef(event.target.value); setEvidenceError(undefined); }} error={evidenceError} disabled={cardBusy} /><TextField label="Platform (optional)" value={platform} onChange={(event) => setPlatform(event.target.value)} disabled={cardBusy} /><TextField label="Creator note (optional)" multiline value={note} onChange={(event) => setNote(event.target.value)} disabled={cardBusy} /><Button type="submit" disabled={cardBusy} fullWidthOnMobile>{cardBusy ? "Submitting…" : "Submit for verification"}</Button></form> : null}
    {publishing.state === "EVIDENCE_SUBMITTED" && role === "CREATOR" ? <Alert tone="warning" title="Submitted for verification">Waiting for the Brand to verify publishing.</Alert> : null}
    {(canVerify || canRequestCorrection) && active ? <section className="collab-publishing-card__verification"><header><div><h6>Compliance check</h6><p>Verify the publishing requirement or request a correction. Settlement remains separate.</p></div><span>Awaiting Brand verification</span></header>{canVerify ? <form className="collab-command-form" onSubmit={(event) => { event.preventDefault(); onVerify(deliverable.deliverableExecutionId, active.publishingEvidenceId, complianceRef.trim() || undefined); }} aria-busy={busyAction === key("verify", active.publishingEvidenceId)}><TextField label="Compliance reference (optional)" value={complianceRef} onChange={(event) => setComplianceRef(event.target.value)} disabled={cardBusy} /><Button type="submit" disabled={cardBusy} fullWidthOnMobile>{busyAction === key("verify", active.publishingEvidenceId) ? "Verifying…" : "Verify publishing"}</Button></form> : null}{canRequestCorrection ? <form className="collab-command-form" onSubmit={requestCorrection} aria-busy={busyAction === key("correct", active.publishingEvidenceId)}><TextField label="Correction reason" multiline value={correctionReason} onChange={(event) => { setCorrectionReason(event.target.value); setCorrectionError(undefined); }} error={correctionError} disabled={cardBusy} /><Button type="submit" variant="secondary" disabled={cardBusy} fullWidthOnMobile>{busyAction === key("correct", active.publishingEvidenceId) ? "Requesting…" : "Request correction"}</Button></form> : null}</section> : null}
    {publishing.state === "COMPLIANCE_VERIFIED" ? <Alert tone="success" title="Publishing verified">The publishing requirement is complete. Settlement status is shown separately.</Alert> : null}
    {publishing.state === "BLOCKED" ? <BlockingCard detail={detail} reason={publishing.blockedReason} actionRequiredBy={deliverable.actionRequiredBy} /> : null}
    <PublishingEvidenceHistory evidence={publishing.evidenceHistory} />
  </article>;
}
