import { Alert } from "../../../../design-system/aurora";
import type { CollaborationDetailResponse } from "../../contracts/collaboration.contracts";

const settlementCopy = { NOT_ELIGIBLE: ["Settlement not ready", "Settlement will become available when the required execution gates are complete."], ELIGIBLE: ["Ready for settlement", "Settlement is ready for processing. No action is required from you."], PROCESSING: ["Settlement processing", "The required payout and refund legs are being processed."], SETTLED: ["Settlement completed", "The required settlement legs are confirmed or not required."] } as const;
const legCopy: Record<string, string> = { NOT_REQUIRED: "Not required", PENDING: "Pending", PROCESSING: "Processing", CONFIRMED: "Confirmed", BLOCKED: "Delayed" };
function money(currency: string | null | undefined, amount: number | null | undefined) { return amount == null ? "Not projected" : `${currency ?? ""} ${amount}`.trim(); }

export function SettlementCard({ detail }: { detail: CollaborationDetailResponse }) {
  const settlement = detail.settlement; const copy = settlementCopy[settlement.state]; const resolution = detail.resolution;
  return <section className="collab-exec-card collab-settlement" aria-labelledby="collab-settlement-title"><h5 id="collab-settlement-title">Settlement execution</h5><Alert tone={settlement.state === "SETTLED" ? "success" : "warning"} title={copy[0]}>{copy[1]}</Alert><dl className="collab-facts">{settlement.creatorSettlementAmount != null ? <div><dt>Creator settlement amount</dt><dd>{money(settlement.currency, settlement.creatorSettlementAmount)}</dd></div> : null}{settlement.brandRefundAmount != null ? <div><dt>Brand refund amount</dt><dd>{money(settlement.currency, settlement.brandRefundAmount)}</dd></div> : null}{settlement.creatorPayoutState ? <div><dt>Creator payout</dt><dd>{legCopy[settlement.creatorPayoutState] ?? "Status available"}</dd></div> : null}{settlement.brandRefundState ? <div><dt>Brand refund execution</dt><dd>{legCopy[settlement.brandRefundState] ?? "Status available"}</dd></div> : null}{settlement.settledAt ? <div><dt>Settled</dt><dd>{new Date(settlement.settledAt).toLocaleString()}</dd></div> : null}<div><dt>Residual settlement</dt><dd>{settlement.residualSettlementPending ? "Pending" : "None pending"}</dd></div></dl>{resolution ? <section className="collab-financial-resolution" aria-labelledby="collab-resolution-summary-title"><h6 id="collab-resolution-summary-title">Financial resolution</h6><dl className="collab-facts"><div><dt>Creator entitlement</dt><dd>{money(resolution.currency, resolution.creatorGrossEntitlementAmount ?? resolution.creatorEntitlementAmount)}</dd></div><div><dt>Brand refund entitlement</dt><dd>{money(resolution.currency, resolution.brandCommercialRefundEntitlementAmount ?? resolution.brandRefundEntitlementAmount)}</dd></div></dl><p>Entitlements are determined separately from payout and refund execution.</p></section> : null}<p>Publishing verification does not itself complete payment.</p></section>;
}
